import React from "react";
import MainHome from "./Components/Home/Index";

// SEO metadata for the homepage with title, description, and keywords
export const metadata = {
  title: "Rido Emirates - Taxi Service in Dubai & Abu Dhabi",
  description:
    "Rido Emirates provides reliable and affordable taxi services for your travel needs across Dubai and Abu Dhabi. Book your ride now for safe, comfortable, and timely transportation.",
  keywords: [
    "Dubai taxi service",
    "Abu Dhabi taxi service",
    "taxi Dubai to Abu Dhabi",
    "taxi service Abu Dhabi to Dubai",
    "Dubai airport taxi",
    "Abu Dhabi airport taxi",
    "taxi booking Dubai",
    "taxi booking Abu Dhabi",
    "Dubai to Abu Dhabi taxi",
    "Abu Dhabi to Dubai taxi",
    "affordable taxi Dubai",
    "affordable taxi Abu Dhabi",
    "taxi ride Dubai",
    "taxi ride Abu Dhabi",
    "Dubai taxi booking",
    "Abu Dhabi taxi booking",
    "reliable taxi service Dubai",
    "reliable taxi service Abu Dhabi",
    "safe taxi service Dubai",
    "safe taxi service Abu Dhabi",
    "comfortable taxi Dubai",
    "comfortable taxi Abu Dhabi",
    "timely taxi service Dubai",
    "timely taxi service Abu Dhabi",
    "local taxi Dubai",
    "local taxi Abu Dhabi",
    "taxi for tourists Dubai",
    "taxi for tourists Abu Dhabi",
    "Dubai taxi fares",
    "Abu Dhabi taxi fares",
    "Dubai to Abu Dhabi taxi fare",
    "Abu Dhabi to Dubai taxi fare",
    "Dubai airport transfer",
    "Abu Dhabi airport transfer",
    "taxi service UAE",
    "Dubai transport",
    "Abu Dhabi transport",
    "Dubai transportation services",
    "Abu Dhabi transportation services",
    "private taxi Dubai",
    "private taxi Abu Dhabi",
    "economy taxi Dubai",
    "luxury taxi Dubai",
    "economy taxi Abu Dhabi",
    "luxury taxi Abu Dhabi",
    "taxi ride booking",
    "airport taxi Dubai",
    "airport taxi Abu Dhabi",
    "chauffeur service Dubai",
    "chauffeur service Abu Dhabi",
    "24/7 taxi service Dubai",
    "24/7 taxi service Abu Dhabi",
    "Dubai car hire",
    "Abu Dhabi car hire",
    "city taxi Dubai",
    "city taxi Abu Dhabi",
    "affordable car hire Dubai",
    "affordable car hire Abu Dhabi",
    "Dubai city transportation",
    "Abu Dhabi city transportation",
    "taxi transportation Dubai",
    "taxi transportation Abu Dhabi",
    "long-distance taxi Dubai",
    "long-distance taxi Abu Dhabi",
    "Dubai to Sharjah taxi",
    "Abu Dhabi to Sharjah taxi",
    "taxi for corporate Dubai",
    "taxi for corporate Abu Dhabi",
    "business taxi Dubai",
    "business taxi Abu Dhabi",
    "taxi services for events Dubai",
    "taxi services for events Abu Dhabi",
    "Dubai to Ajman taxi",
    "Abu Dhabi to Ajman taxi",
    "taxi Dubai Marina",
    "taxi Abu Dhabi Marina",
    "affordable taxi for families Dubai",
    "affordable taxi for families Abu Dhabi",
    "executive taxi Dubai",
    "executive taxi Abu Dhabi",
    "Dubai to Fujairah taxi",
    "Abu Dhabi to Fujairah taxi",
    "taxi for medical appointments Dubai",
    "taxi for medical appointments Abu Dhabi",
    "Dubai hotel taxi",
    "Abu Dhabi hotel taxi",
    "group taxi Dubai",
    "group taxi Abu Dhabi",
    "taxi services for tourists UAE",
    "taxi for weddings Dubai",
    "taxi for weddings Abu Dhabi",
    "taxi services UAE",
    "taxi Dubai to Al Ain",
    "taxi Abu Dhabi to Al Ain",
    "fast taxi Dubai",
    "fast taxi Abu Dhabi",
    "direct taxi Dubai to Abu Dhabi",
    "direct taxi Abu Dhabi to Dubai"
  ]
};

const Home = () => {
  return (
    <main>
      <MainHome />
    </main>
  );
};

export default Home;
